export const SET_BOOK_MODAL_OPEN = "SET_BOOK_MODAL_OPEN";
export const SET_FILTERS_MODAL_OPEN = "SET_FILTERS_MODAL_OPEN";
export const SET_CURRENT_BOOK = "SET_CURRENT_BOOK";
export const SET_BOOK_MODE = "SET_BOOK_MODE";
export const SET_AUTHORS = "SET_AUTHORS";
export const SET_FILTER_TYPE = "SET_FILTER_TYPE";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
export const SET_ALL_BOOKS = "SET_ALL_BOOKS";